[project]
name = "oai-coding-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nest-asyncio>=1.6.0",
    "openai-agents[litellm]>=0.0.15",
    "pydantic-ai[logfire]>=0.2.4",
    "python-dotenv>=1.0.0",
]
