from typing import Any, Dict

class MCPServer:
    params: Dict[str, Any]

    async def __aenter__(self) -> Any: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> Any: ...

class MCPServerStdio(MCPServer):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def create_streams(self) -> Any: ...
