apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sc-azure-disk-premium-zrs.yaml
  - keyvault-secretstore.yaml

patches:
  - path: cluster-keyvault-patch.yaml

images:
  # For AKS, use the container registry image (set by CI/CD or manually)
  - name: python-app
    newName: <PY_APP_REGISTRY>/python-app
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - literals:
      - email=PLACEHOLDER_PGADMIN_EMAIL
      - password=PLACEHOLDER_PGADMIN_PASSWORD
    name: pgadmin-credentials
