apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sc-azure-disk-premium-zrs.yaml
  - keyvault-secretstore.yaml

patchesStrategicMerge:
  - cluster-keyvault-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: pgadmin-credentials
    literals:
      - email=PLACEHOLDER_PGADMIN_EMAIL
      - password=PLACEHOLDER_PGADMIN_PASSWORD
