apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vector
spec:
  instances: 1
  storage:
    storageClass: standard
  walStorage:
    storageClass: standard
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "500m"
