apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pg-nodeport.yaml
  - pgadmin-dev-secret.yaml

patchesStrategicMerge:
  - cluster-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: db-user-pass
    literals:
      - username=app
      - password=PLACEHOLDER_PG_PASSWORD
