apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: cnpg-system
type: Opaque
data:
  # dev@example.com (base64 encoded)
  email: ZGV2QGV4YW1wbGUuY29t
  # devpass (base64 encoded)
  password: ZGV2cGFzcw==
