# .github/workflows/oai-agent.yml
name: OAI Coding Agent

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

jobs:
  run-agent:
    # Only proceed if:
    #   - on opened: issue has @oai in body OR already labeled "oai"
    #   - on labeled: the new label is exactly "oai"
    #   - on comment: the comment body contains "@oai"
    if: >-
      (
        github.event_name == 'issues' &&
        (
          (github.event.action == 'opened' &&
            (
              contains(github.event.issue.labels.*.name, 'oai') ||
              contains(github.event.issue.body, '@oai')
            )
          ) ||
          (github.event.action == 'labeled' && github.event.label.name == 'oai')
        )
      ) ||
      (
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '@oai')
      )

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # allow pushing back
          persist-credentials: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Set up Node.js (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Create a fresh branch for the agent
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          BRANCH="oai/issue-${ISSUE_NUMBER}"
          git checkout -b "$BRANCH"
          git push --set-upstream origin HEAD

      - name: Run OAI coding agent in headless mode
        env:
          RICH_FORCE_TERMINAL: "1" # these provide pretty logs in GHA
          TTY_COMPATIBLE: "1"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          uv sync
          source .venv/bin/activate
          oai --prompt - << 'PROMPT_END'
          Complete the following GitHub issue:
          Repository: ${{ github.event.repository.html_url }}
          Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}

          Body:
          ${{ github.event.issue.body }}
          PROMPT_END
