apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cnpg-monitor
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: pg-vector
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
